version: '3.8'
services:

  # Database PostgreSQL
  postgres:
    image: postgres:13
    container_name: openmusic_db
    restart: always
    environment:
      POSTGRES_USER: openmusic
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: openmusicdb
    ports:
      - '5432:5432'

  # Cache (Redis)
  redis:
    image: redis:latest
    container_name: openmusic_redis
    restart: always
    ports:
      - '6379:6379'

  # Message Broker (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: openmusic_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: openmusic
      RABBITMQ_DEFAULT_PASS: password123
    ports:
      - '5672:5672'
      - '15672:15672'